name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run:
        - sudo apt-get update
        - sudo apt-get install -y \ 
              libspdlog-dev \
              libgtest-dev \
              cmake \
              g++ \
              # end of dependencies

    - name: Create build directory
      run: mkdir build && cd build

    - name: Configure CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=Release
      working-directory: ./build

    - name: Build
      run: cmake --build .
      working-directory: ./build

    - name: Run tests
      run: ./ctest
      working-directory: ./build